### ISSUE TITLE
Unhandled Rejection

### ISSUE THREAD

**Issue by yamifr07** [e-oj/Fawn#53]
Suddenly my server stop working and throws the following error. For the moment, I resolved it by dropping the ojlinttaskcollections db.
 
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property '_id' of undefined
    at rollbackSave (/home/inamu/webserver/node_modules/fawn/lib/roller.js:137:30)
    at /home/inamu/webserver/node_modules/fawn/lib/roller.js:98:39
    at tryCatcher (/home/inamu/webserver/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/inamu/webserver/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/inamu/webserver/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/home/inamu/webserver/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/home/inamu/webserver/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/home/inamu/webserver/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/inamu/webserver/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by e-oj** [comment]
What version of Fawn? and can you share the code that causes that error?

**Comment by yamifr07** [comment]
2.1.5
I found the error was because I forgot to call next on pre save in the second transaction

`let transaction = Fawn.Task();

			transaction.save('User', {
				email: req.body.user.email
			});

			let data = lodash.pick(req.body, fields);
			data.user = {$ojFuture: '0._id'};
			transaction.save('Organization', data);`

**Comment by e-oj** [comment]
The error bubbles up to the user when something goes wrong that the user needs to know about. You can always catch any errors that occur to prevent crashing.

```javascript
let task = Fawn.Task();

task.save(...);
task.update(...);

try{
  let result = await task.run();
}
catch(err){
  console.log(err.message);
}
```

**Comment by yamifr07** [comment]
I use the following code but wasn't enough

`
				transaction.run({useMongoose: true})
				.then((results) => {})
				.catch((err) => {})
`

**Comment by e-oj** [comment]
That's strange. I'll look into it.
